-- Catálogos maestros (POMA), generados desde scripts/data/*.csv.
--
-- Van en una migración, y no en scripts/import-ara.ts, porque son datos de
-- configuración sin ningún dato personal: pueden vivir en git y deben existir en
-- todos los entornos. Los productores y las entidades, que sí llevan datos
-- personales, se importan aparte con el script y nunca se versionan.
--
-- Las familias se normalizan aquí igual que en el script (el Excel trae
-- "Fruita seca", "Fruit vermell" y "Hort Tub/Bul/Arr").
-- Para regenerar este archivo, ver la nota en AGENTS.md §6.

insert into causas (codigo, nombre) values
  ('CE', 'Criteris Estètics'),
  ('CL', 'Clima'),
  ('CN', 'Canalització'),
  ('EX', 'Excedent'),
  ('FC', 'Final Cultiu'),
  ('GD', 'Gestió Deficient'),
  ('MQ', 'Maquila'),
  ('PR', 'Preu')
on conflict (codigo) do update set nombre = excluded.nombre;

insert into productos (nombre, familia, eur_kg) values
  ('Albercoc', 'Fruita Dolça', 1.0),
  ('Albergínia', 'Horta Fruit', 1.0),
  ('Alfabrega', 'Horta Fulla', 1.0),
  ('All', 'Horta Tub/Bul/Arr', 1.0),
  ('Alvocat', 'Fruita Exòtica', 1.0),
  ('Api', 'Horta Fulla', 1.0),
  ('Arròs', 'Varis', 1.0),
  ('Blat de moro', 'Varis', 1.0),
  ('Bleda', 'Horta Fulla', 1.0),
  ('Bolet', 'Bolets', 1.0),
  ('Bròquil', 'Horta Flor', 1.0),
  ('Calçot', 'Horta Tub/Bul/Arr', 1.0),
  ('Carbassa', 'Horta Fruit', 1.0),
  ('Carbassó', 'Horta Fruit', 1.0),
  ('Card', 'Horta Fulla', 1.0),
  ('Carxofa', 'Horta Flor', 1.0),
  ('Ceba', 'Horta Tub/Bul/Arr', 1.0),
  ('Cigrons', 'Horta Tub/Bul/Arr', 1.0),
  ('Cirera', 'Fruita Dolça', 1.0),
  ('Coco', 'Fruita Exòtica', 1.0),
  ('Codony', 'Fruita Dolça', 1.0),
  ('Cogombre', 'Horta Fruit', 1.0),
  ('Col', 'Horta Fulla', 1.0),
  ('Col de Brussel·les', 'Horta Fulla', 1.0),
  ('Coliflor', 'Horta Flor', 1.0),
  ('Garrofa', 'Fruita Seca', 1.0),
  ('Enciam', 'Horta Fulla', 1.0),
  ('Espàrrec', 'Horta Fulla', 1.0),
  ('Espinac', 'Horta Fulla', 1.0),
  ('Fava', 'Horta Fruit', 1.0),
  ('Fesol', 'Horta Fruit', 1.0),
  ('Figa', 'Fruita Dolça', 1.0),
  ('Fonoll', 'Horta Tub/Bul/Arr', 1.0),
  ('Gerd', 'Fruita Vermella', 1.0),
  ('Julivert', 'Horta Fulla', 1.0),
  ('Kaki', 'Fruita Dolça', 1.0),
  ('Kiwi', 'Fruita Exòtica', 1.0),
  ('Lactic', 'Varis', 1.0),
  ('Llima', 'Fruita Cítrics', 1.0),
  ('Llimona', 'Fruita Cítrics', 1.0),
  ('Maduixa', 'Horta Fruit', 1.0),
  ('Magrana', 'Fruita Dolça', 1.0),
  ('Mandarina', 'Fruita Cítrics', 1.0),
  ('Mango', 'Fruita Exòtica', 1.0),
  ('Meló', 'Horta Fruit', 1.0),
  ('Menta', 'Varis', 1.0),
  ('Mongeta', 'Horta Fruit', 1.0),
  ('Moniato', 'Horta Tub/Bul/Arr', 1.0),
  ('Nabiu', 'Fruita Vermella', 1.0),
  ('Nap', 'Horta Tub/Bul/Arr', 1.0),
  ('Nectarina', 'Fruita Dolça', 1.0),
  ('Nespre', 'Fruita Dolça', 1.0),
  ('Nous', 'Fruita Seca', 1.0),
  ('Nyora', 'Horta Fruit', 1.0),
  ('Olives', 'Varis', 1.0),
  ('Ou', 'Varis', 1.0),
  ('Paraguaià', 'Fruita Dolça', 1.0),
  ('Pastanaga', 'Horta Tub/Bul/Arr', 1.0),
  ('Patata', 'Horta Tub/Bul/Arr', 1.0),
  ('Pebrot', 'Horta Fruit', 1.0),
  ('Pera', 'Fruita Dolça', 1.0),
  ('Pèsol', 'Horta Fruit', 1.0),
  ('Pinya', 'Fruita Exòtica', 1.0),
  ('Plàtan', 'Fruita Exòtica', 1.0),
  ('Poma', 'Fruita Dolça', 1.0),
  ('Porro', 'Horta Tub/Bul/Arr', 1.0),
  ('Préssec', 'Fruita Dolça', 1.0),
  ('Pruna', 'Fruita Dolça', 1.0),
  ('Raim', 'Fruita Dolça', 1.0),
  ('Rave', 'Horta Tub/Bul/Arr', 1.0),
  ('Remolatxa', 'Horta Tub/Bul/Arr', 1.0),
  ('Rucula', 'Horta Fulla', 1.0),
  ('Sindria', 'Horta Fruit', 1.0),
  ('Soja', 'Varis', 1.0),
  ('Suc', 'Varis', 1.0),
  ('Taronja', 'Fruita Cítrics', 1.0),
  ('Tomàquet', 'Horta Fruit', 1.0),
  ('Varis', 'Varis', 1.0),
  ('Xampinyó', 'Bolets', 1.0),
  ('Xicòria', 'Horta Tub/Bul/Arr', 1.0),
  ('Xirimoia', 'Fruita Exòtica', 1.0),
  ('Xirivia', 'Horta Tub/Bul/Arr', 1.0),
  ('Yuca', 'Horta Tub/Bul/Arr', 1.0),
  ('RETORN', 'Indeterminat', 1.0),
  ('Avellana', 'Fruita Seca', 1.0),
  ('Ametlla', 'Fruita Seca', 1.0),
  ('Escarola', 'Horta Fulla', 1.0),
  ('Brócoli', 'Horta Flor', 1.0),
  ('Mores', 'Fruita Vermella', 1.0),
  ('Colrave', 'Horta Tub/Bul/Arr', 1.0)
on conflict (nombre) do update set familia = excluded.familia, eur_kg = excluded.eur_kg;

insert into factores_conversion (producto, kg_por_unidad) values
  ('COL', 1.5),
  ('CALÇOTS (manat 25u)', 2.5),
  ('BROCOLI', 1.5),
  ('CEBA', 1),
  ('CEBA  TENDRA', 0.5),
  ('ENCIAM TROCADERO', 0.5),
  ('ENCIAM FULLA DE ROURE', 0.5),
  ('ENCIAM ICEBERG', 1),
  ('ENCIAM LLARG', 1),
  ('ENCIAM MARAVILLA', 0.5),
  ('ALLS', 0.33),
  ('PASTANAGA MANAT', 1),
  ('PORRO MANAT', 1),
  ('API', 1),
  ('BLEDES MANAT', 1)
on conflict (producto) do update set kg_por_unidad = excluded.kg_por_unidad;
